### ISSUE TITLE
Using model 'dna_r10.4.1_400bps_9mer' - Key error 

### ISSUE THREAD

**Issue by denisbeslic** [skovaka/uncalled4#12]
Hi,

I am running uncalled4 using the following command:

```
uncalled4 align data/zymo-human/GRCh38_no_alt.fna PGXX22563_reads.slow5 \
--bam-in target.bam --eventalign-out data/events-train.tsv \
--eventalign-flags print-read-names,signal-index,samples \
--pore-model dna_r10.4.1_400bps_9mer
```

I get the following error message:
```
Traceback (most recent call last):
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 824, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2989, in _get_loc_level
    return (self._engine.get_loc(key), None)
  File "pandas/_libs/index.pyx", line 827, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
KeyError: ('', '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/XXX/.local/bin/uncalled4", line 8, in <module>
    sys.exit(main())
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/__main__.py", line 382, in main
    ret = fn(conf=conf)
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/align.py", line 52, in align
    dtw_single(conf)
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/align.py", line 172, in dtw_single
    for aln in tracks.bam_in.iter_alns():
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/io/bam.py", line 318, in iter_alns
    aln = self.sam_to_aln(sam)
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/io/bam.py", line 391, in sam_to_aln
    moves = sam_to_ref_moves(self.conf, self.tracks.index, read, sam)
  File "/XXX/.local/lib/python3.8/site-packages/uncalled4/moves.py", line 94, in sam_to_ref_moves
    shift = MOVE_SHIFTS[PoreModel.PRESET_MAP.loc[conf.pore_model.get_workflow(), "ont_model"]]
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
    return self._getitem_tuple(key)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1280, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 976, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1077, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1343, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1293, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4088, in xs
    loc, new_index = index._get_loc_level(key, level=0)
  File "/XXX/.local/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2991, in _get_loc_level
    raise KeyError(key) from err
KeyError: ('', '')
```

It seems to be a mistake with the pore model file?

Thanks for your help!
Denis

**Comment by skovaka** [comment]
I think it's an issue with determining the basecaller parameters. Try adding these flags: `--flowcell FLO-MIN114 --kit SQK-LSK114`. Those can usually be detected from the SLOW5/POD5/FAST5 file, but the format isn't always consistent. It also shouldn't be necessary if you're defining the pore model explicitly, but the current implementation always requires those parameters. I'll work on simplifying and clarifying that

**Comment by denisbeslic** [comment]
Yes, that worked. Thank you!
