### ISSUE TITLE
KeyError: ('FLO-PRO114M', 'SQK-RNA002')

### ISSUE THREAD

**Issue by iremtll** [skovaka/uncalled4#19]
Hello, 

I encounter an error when I try to run uncalled4 align like that:
`uncalled4 align /UCSC_GRCm38/refMrna.fa /pod5files/ --bam-in /merged.bam --eventalign-out events.tsv -p 10 --eventalign-flags print-read-names,samples --flowcell FLO-PRO114M --kit SQK-RNA002
`

Error code: 
```
Loading read index '/pod5files/read_index.txt'

Traceback (most recent call last):
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 3220, in _get_loc_level
    return (self._engine.get_loc(key), None)
  File "index.pyx", line 776, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2152, in pandas._libs.hashtable.UInt64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2176, in pandas._libs.hashtable.UInt64HashTable.get_item
KeyError: 2490

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/nanocaller_env/bin/uncalled4", line 8, in <module>
    sys.exit(main())
  File "/env/nanocaller_env/lib/python3.10/site-packages/uncalled4/__main__.py", line 382, in main
    ret = fn(conf=conf)
  File "/env/nanocaller_env/lib/python3.10/site-packages/uncalled4/align.py", line 54, in align
    dtw_pool(conf)
  File "/env/nanocaller_env/lib/python3.10/site-packages/uncalled4/align.py", line 110, in dtw_pool
    tracks = Tracks(conf=conf)
  File "/env/nanocaller_env/lib/python3.10/site-packages/uncalled4/tracks.py", line 885, in __init__
    self._init_new(*args, **kwargs)
  File "/env/nanocaller_env/lib/python3.10/site-packages/uncalled4/tracks.py", line 921, in _init_new
    pm.name = PoreModel.PRESET_MAP.loc[pm.get_workflow(), "preset_model"]
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1368, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1041, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1153, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/generic.py", line 4293, in xs
    loc, new_index = index._get_loc_level(key, level=0)
  File "/env/nanocaller_env/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 3222, in _get_loc_level
    raise KeyError(key) from err
KeyError: ('FLO-PRO114M', 'SQK-RNA002')
```

Many thanks in advance!

**Comment by skovaka** [comment]
Are you using the "dev" branch? I haven't finalized support for RNA004 quite yet, but I have a version which works pretty well on the dev branch, which I plan to merge with main soon

**Comment by iremtll** [comment]
Oh no I didn't use it. Now, I switched to dev and it works. Thank you very much for your quick reply! :)
