### ISSUE TITLE
uncalled4 align: missing tag "ts"

### ISSUE THREAD

**Issue by BrendanBeahan** [skovaka/uncalled4#30]
Hello, I'm sorry if this is rather elementary.

But I attempted to generate the appropriate input bam files for uncalled4 align via the following command: 

`guppy_basecaller -i /fast5_directory -r -x 'auto' -s /output_bams --moves_out --bam_out --align_ref /Mus_musculus_custom_transcript_fasta.fa -c rna_r9.4.1_70bps_hac.cfg`

However, when I then combine the subsequence bam files and submit them to uncalled4 align I get a "missing ts tag" error.

Code:
`  uncalled4 align --flowcell FLO-MIN106 --kit SQK-RNA002 ${transcriptome_fasta} ${fast5} --bam-in ${input_bam} --eventalign-out ${params.resultsDir}/RNA002_mouse_maestri_KO/eventalign.txt
`

Error:
`Command error:
  Loading read index 'workspace/read_index.txt'
  Auto-detected flowcell='FLO-MIN106' kit='SQK-RNA002'
  Using model 'rna_r9.4.1_70bps_5mer'
  Traceback (most recent call last):
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/bin/uncalled4", line 8, in <module>
      sys.exit(main())
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/__main__.py", line 382, in main
      ret = fn(conf=conf)
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/align.py", line 52, in align
      dtw_single(conf)
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/align.py", line 172, in dtw_single
      for aln in tracks.bam_in.iter_alns():
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/io/bam.py", line 318, in iter_alns
      aln = self.sam_to_aln(sam)
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/io/bam.py", line 391, in sam_to_aln
      moves = sam_to_ref_moves(self.conf, self.tracks.index, read, sam)
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/moves.py", line 57, in sam_to_ref_moves
      read_moves = sam_to_read_moves(read, sam)
    File "/user/brussel/110/vsc11010/.conda/envs/uncalled4-env/lib/python3.8/site-packages/uncalled4/moves.py", line 46, in sam_to_read_moves
      template_start = sam.get_tag("ts")
    File "pysam/libcalignedsegment.pyx", line 2507, in pysam.libcalignedsegment.AlignedSegment.get_tag
    File "pysam/libcalignedsegment.pyx", line 2546, in pysam.libcalignedsegment.AlignedSegment.get_tag
  KeyError: "tag 'ts' not present"`
  
  And indeed I do not see the ts flag when I investigate individual bam files, though the mv tag is there. If you had any thoughts on how I could address this I'd appreciate it!

**Comment by skovaka** [comment]
What version of guppy are you using? If the "mv" tag is present but not "ts", then that sounds like a guppy error. Unfortunately, I don't think ONT is supporting Guppy anymore, they've now transitioned to Dorado.

I believe guppy excludes "mv" and "ts" tags from supplemental and secondary alignments, and we provided the `scripts/bamprep.py` script to fix that. Also, in minimap2 spliced RNA alignment, the "ts" tag is used to label splice site strand, which can sometimes override the basecaller ts flag depending on how you convert it. It doesn't sound like that's your issue, but just mentioning since it's related.
