### ISSUE TITLE
Specify two bam files for refstats ks test

### ISSUE THREAD

**Issue by kayleewatson** [skovaka/uncalled4#32]
Hi,

I'm using the latest 4.1.0 version and refstats works perfectly for a single bam input, but how does the --bam-in flag work for multiple bam files? I'm wanting to compute ks stat. I tried just listing both bam files after --bam-in, but I got the error below:

```Traceback (most recent call last):
  File "/usr/local/packages/miniconda3/envs/uncalled4/bin/uncalled4", line 8, in <module>
    sys.exit(main())
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/__main__.py", line 358, in main
    ret = fn(conf=conf)
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/stats/refstats.py", line 59, in refstats
    for chunk in tracks.iter_refs():
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1359, in iter_refs
    chunks[i] = next(layer_iters[i], (None, None))
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/io/bam.py", line 559, in iter_refs
    new_alns = pd.DataFrame(new_alns, columns=new_alns[0]._fields).set_index("id")
IndexError: list index out of range
```

**Comment by skovaka** [comment]
Sorry for the delayed response! Listing both files after the flag should work: `--bam-in file1.bam file2.bam`. Just make sure both BAM files were output by `uncalled4 align` or `convert`, and maybe try putting the `--bam-in ...` flag at the end of your command.

You could also try computing other statistics in addition to KS stats: `--layers dtw.current --stats ks mean`, or let me know if it works with two BAM files and no KS stats (`--stats mean`). I'm wondering if the bug is when computing KS stats, or just when parsing two BAM files at once.

**Comment by kayleewatson** [comment]
Thank you for your response, I just tried with some other files and it looks like one of my bam files is the problem (I'm doing some filtering so I probably just screwed up the format somewhere along the way). It's working by just listing the bam files after the flag like you mentioned. I appreciate the clarification on the command, and this tool has been extremely helpful!

**Comment by kayleewatson** [comment]
Hi again,

I'm actually having another issue running the refstats KS test. Here's my command:

`uncalled4 refstats -p 4 -c --ref [ref_file] -o [out_file] --layers dtw.current --stats ks --bam-in [bam1] [bam2]`

I keep getting the following error:

`Traceback (most recent call last):
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 1664, in _get_level_number
    level = self.names.index(level)
ValueError: 2 is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/packages/miniconda3/envs/uncalled4/bin/uncalled4", line 8, in <module>
    sys.exit(main())
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/__main__.py", line 358, in main
    ret = fn(conf=conf)
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/stats/refstats.py", line 59, in refstats
    for chunk in tracks.iter_refs():
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1390, in iter_refs
    ret = self._tables_to_tracks(coords, alns, layers)
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1556, in _tables_to_tracks
    tracks.calc_refstats()
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1323, in calc_refstats
    cmpstats = cmp_groups.apply(ks).reorder_levels([2,0,1,3],axis=1)
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/frame.py", line 7875, in reorder_levels
    result.columns = result.columns.reorder_levels(order)
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2557, in reorder_levels
    order = [self._get_level_number(i) for i in order]
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2557, in <listcomp>
    order = [self._get_level_number(i) for i in order]
  File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 1678, in _get_level_number
    raise IndexError(
IndexError: Too many levels: Index has only 2 levels, not 3
`

This happens with every set of bam files I try, regardless of the samples. I also tried with some data that had worked fine prior to the latest Uncalled4 update, but with the new version I now get this error. Do you know what might be causing it? It will often still have an output file, but only a partial one, where it stops part of the way into the reference genome.

**Comment by IsisvanLoenen** [comment]
Hi,
I'm having the same issue as mentioned above by Kaylee Watson. Is there a solution for this issue?

> Hi again,
> 
> I'm actually having another issue running the refstats KS test. Here's my command:
> 
> `uncalled4 refstats -p 4 -c --ref [ref_file] -o [out_file] --layers dtw.current --stats ks --bam-in [bam1] [bam2]`
> 
> I keep getting the following error:
> 
> `Traceback (most recent call last): File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 1664, in _get_level_number level = self.names.index(level) ValueError: 2 is not in list
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/packages/miniconda3/envs/uncalled4/bin/uncalled4", line 8, in sys.exit(main()) File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/**main**.py", line 358, in main ret = fn(conf=conf) File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/stats/refstats.py", line 59, in refstats for chunk in tracks.iter_refs(): File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1390, in iter_refs ret = self._tables_to_tracks(coords, alns, layers) File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1556, in _tables_to_tracks tracks.calc_refstats() File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/uncalled4/tracks.py", line 1323, in calc_refstats cmpstats = cmp_groups.apply(ks).reorder_levels([2,0,1,3],axis=1) File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/frame.py", line 7875, in reorder_levels result.columns = result.columns.reorder_levels(order) File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2557, in reorder_levels order = [self._get_level_number(i) for i in order] File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 2557, in order = [self._get_level_number(i) for i in order] File "/usr/local/packages/miniconda3/envs/uncalled4/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 1678, in _get_level_number raise IndexError( IndexError: Too many levels: Index has only 2 levels, not 3 `
> 
> This happens with every set of bam files I try, regardless of the samples. I also tried with some data that had worked fine prior to the latest Uncalled4 update, but with the new version I now get this error. Do you know what might be causing it? It will often still have an output file, but only a partial one, where it stops part of the way into the reference genome.

**Comment by tnanhthu** [comment]
> This happens with every set of bam files I try, regardless of the samples. I also tried with some data that had worked fine prior to the latest Uncalled4 update, but with the new version I now get this error. Do you know what might be causing it? It will often still have an output file, but only a partial one, where it stops part of the way into the reference genome.

Hi @kayleewatson, do you remember which Uncalled4 version that worked for `--stats ks` flag? Thanks in advance.

**Comment by jadegoveas2** [comment]
I am having this same issue. Is there a solution?
