### ISSUE TITLE
ModuleNotFoundError: No module named 'memray'

### ISSUE THREAD

**Issue by denisbeslic** [skovaka/uncalled4#7]
I have installed uncalled4 succesfully via pip. However when I try to run the align function I get the following error:
```
Traceback (most recent call last):
  File "xxx/.local/bin/uncalled4", line 8, in <module>
    sys.exit(main())
  File "xxx/.local/lib/python3.8/site-packages/uncalled4/__main__.py", line 375, in main
    m = importlib.import_module(f".{module}", "uncalled4")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "xxx/.local/lib/python3.8/site-packages/uncalled4/align.py", line 30, in <module>
    import memray
ModuleNotFoundError: No module named 'memray'
```

**Comment by skovaka** [comment]
I just updated the pypi package to the latest version, so that issue should be fixed now!
